blog/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
#sys.path.insert(0, '/Users/adiop.PC-CLEGE/Documents/cloudsen/blog/ftp')
from  .views import UserViewSet, GroupViewSet



router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ftp.urls')),
    path('myaccount/', include('myaccount.urls')),
    path('emailusers/', include('ldap.urls')),
    path('api/', include(router.urls)),
    path('api/api-auth/', include('rest_framework.urls', namespace='rest_framework')),

]

ftp/urls.py
from django.urls import path, include

from .views import views

urlpatterns = [
    path('', views.index, name='home'),
    path('ftp/<int:pk>', views.t_user_detail, name='t_user_detail'),
    path('ftp/<int:pk>/edit/', views.t_user_edit, name='t_user_edit'),
    path('ftp/<int:pk>/delete', views.t_user_delete, name='t_user_delete'),
    path('ftp/addaccount/', views.t_user_add, name='t_user_add'),
    path(r'^search/$', views.index, name='t_user_search'),

]

ldap/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='emailusers'),
    path('<int:mpk>', views.email_detail, name='t_email_detail'),
    path('<int:mpk>/edit/', views.t_email_edit, name='t_email_edit'),
    path('<int:mpk>/delete', views.t_email_delete, name='t_email_delete'),
    path('addaccount/', views.t_email_add, name='t_email_add'),
]

ldap/models.py
from django.db import models

# Create your models here.

ftp/forms/forms.py
from ..models.models import T_user
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, Div, ButtonHolder
from bootstrap_datepicker_plus import DateTimePickerInput, DatePickerInput
from bootstrap3_datetime.widgets import DateTimePicker
from crispy_forms.bootstrap import StrictButton

ACTIF = (
        ('', 'Selectionner...'),
        ('1', 'Actif'),
        ('0', 'Desactive'),
    )
class TuserForms(forms.ModelForm):
    ftpUsername = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'utilisateur'}))
    ftpPassword = forms.CharField(widget=forms.PasswordInput())
    nom = forms.CharField(
        label='Nom',
        widget=forms.TextInput(attrs={'placeholder': 'Entrez le nom'})
    )
    societe = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Nom Societe'})
    )
    contact_interne = forms.CharField(
        label='Contact Interne',
        widget=forms.TextInput(attrs={'placeholder': 'Le contact interne'})
    )
    actif = forms.ChoiceField(choices=ACTIF)
    telephone = forms.CharField(label='Telephone')
    dateExpiration = forms.DateTimeField(widget=DatePickerInput(options={
                    "format": "YYYY-MM-DD",  # moment date-time format
                    "showClose": True,
                    "showClear": True,
                    "showTodayButton": True,


                }
    )
    )

    def __init__(self, *args, **kwargs):
        super(TuserForms, self).__init__(*args, **kwargs)


        self.fields['ftpUsername'].label = "nom utilisateur"
        self.fields['ftpPassword'].label = "mot de passe"
        self.fields['nom'].label = "nom client"
        self.fields['societe'].label = "Compagny name"
        self.fields['telephone'].label = "telephone"
        self.fields['contact_interne'].label = "contact interne"
        self.fields['actif'].label = "actif/inactif"
        self.fields['ftpHomeDir'].label = "repertoire ftp"
        self.fields['dateExpiration'].label = "%s (AAAA-MM-JJ)" % "Jour Expiration"


        # customiser ton formulaire
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper._form_action = ''
        # id et la classe bootstrap de ton formulaire
        self.helper.form_class = 'form-horizontal'
        self.helper.form_id = 'registration-form'
        # Taille des labels et des champs sur la grille
        self.helper.label_class = 'col-md-8'
        self.helper.field_class = 'col-md-8'
        self.helper.layout = Layout(

            Row(
                Column('ftpUsername', css_class='form-group col-md-6 mb-0'),
                Column('ftpPassword', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('nom', css_class='form-group col-md-4 mb-0'),
                Column('societe', css_class='form-group col-md-4 mb-0'),
                Column('contact_interne',css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),

            Row(
                Column('telephone', css_class='form-group col-md-4 mb-0'),
                Column('ftpHomeDir', css_class='form-group col-md-8 mb-0'),
                css_class='form-row'
            ),

            Row(
                Column('actif', css_class='form-group col-md-4 mb-0'),
                Column('dateExpiration', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Submit('submit', 'Enregistrer')

        )

    class Meta:
        model = T_user
        fields = ('ftpUsername', 'ftpPassword', 'actif', 'ftpHomeDir', 'nom', 'societe', 'telephone', 'contact_interne', 'dateExpiration')

        # fields = '__all__'
        widgets = {
            #'dateExpiration': DatePickerInput(format='%Y/%m/%d HH:mm'),
            'dateExpiration': DatePickerInput(),

        }

ldap/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib import messages
from django.shortcuts import render
import ldap3
from ldap3 import Server, Connection, ALL, SUBTREE, MODIFY_REPLACE
from ldap3.core.exceptions import LDAPException, LDAPBindError
from . import getuidnumber

from .forms import EmailForm
# Create your views here.


def connect_ldap_server():
    try:

        # Provide the hostname and port number of the openLDAP
        server_uri = f"ldap://www.adiop.fr:389"
        server = Server(server_uri, get_info=ALL)
        # username and password can be configured during openldap setup
        connection = Connection(server,
                     user='uid=adiop,dc=adiop,dc=net',
                     password='UtBX4PzS')
        bind_response = connection.bind()  # Returns True or False
    except LDAPBindError as e:
        connection = e

@login_required(login_url='acceslogin')
def index(request):
    server_uri = f"ldap://www.adiop.fr:389"
    server = Server(server_uri, get_info=ALL)
    connection = Connection(server,
                            user='uid=adiop,dc=adiop,dc=net',
                            password='UtBX4PzS')
    bind_response = connection.bind()
    # Provide a search base to search for.
    search_base = 'ou=Public,dc=adiop,dc=net'
    # provide a uidNumber to search for. '*" to fetch all users/groups
    search_filter = '(uid=*)'

    # Establish connection to the server
    ldap_conn = connection
    try:
        # only the attributes specified will be returned


        ldap_conn.search('ou=Public,dc=adiop,dc=net', '(&(objectclass=*))',
        #ldap_conn.search('ou=Public,dc=adiop,dc=net', '(& (objectclass= *)(uidNumber=510))',

                    attributes=['uid', 'mail', 'displayName', 'uidNumber'])
        # search will not return any values.
        # the entries method in connection object returns the results
        emailis = connection.entries
        emailist = [i for i in emailis if i is not None]
        #print(emailist)
    except LDAPException as e:
        results = e



    paginator = Paginator(emailist, 12)
    page = request.GET.get('page')
    emailist = paginator.get_page(page)

    context = {'emailist': emailist}
    return render(request, 'emailusers.html', context)

@login_required(login_url='acceslogin')
def indexb(request):
    total_entries = 0
    server_uri = f"ldap://www.adiop.fr:389"
    server = Server(server_uri, get_info=ALL)
    c = Connection(server, user='uid=adiop,dc=adiop,dc=net', password='UtBX4PzS')
    bind_response = c.bind()

    c.search(search_base='ou=Public,dc=adiop,dc=net',
             search_filter='(objectClass=*)',
             search_scope=SUBTREE,
             attributes=['uid', 'mail', 'displayName', 'uidNumber'],
             paged_size=5)
    total_entries += len(c.response)
    #for entry in c.entries:
        # print(entry['dn'], entry['attributes'])
        #print(entry.uid.value, entry.displayName.value, entry.mail.value)

    cookie = c.result['controls']['1.2.840.113556.1.4.319']['value']['cookie']
    while cookie:
        c.search(search_base='ou=Public,dc=adiop,dc=net',
                 search_filter='(objectClass=*)',
                 search_scope=SUBTREE,
                 attributes=['uid', 'mail', 'displayName', 'uidNumber'],
                 paged_size=5,
                 paged_cookie=cookie)
        total_entries += len(c.response)
        cookie = c.result['controls']['1.2.840.113556.1.4.319']['value']['cookie']
        for entry in c.entries:
             print(entry['dn'], entry['attributes'])
             print(entry.uid.value, entry.displayName.value, entry.mail.value)

    print('Total entries retrieved:', total_entries)
    emailistb = c.entries
    context = {'emailist': emailistb}
    return render(request, 'emailusers.html', context)


@login_required(login_url='acceslogin')
def email_detail(request, mpk):
    server_uri = f"ldap://www.adiop.fr:389"
    server = Server(server_uri, get_info=ALL)
    connection = Connection(server,
                            user='cn=admin,dc=adiop,dc=net',
                            password='UtBX4PzS')
    bind_response = connection.bind()
    search_base = 'ou=Public,dc=adiop,dc=net'
    mpkey = mpk

    search = "(uidNumber={})".format(mpkey)
    search_filter = search
    ldap_conn = connection
    try:
        ldap_conn.search(search_base=search_base,
                         search_filter=search_filter,
                         search_scope=SUBTREE,
                         attributes=['uidNumber', 'uid', 'mail', 'userPassword', 'displayName', 'vacationInfo', 'vacationActive', 'telephoneNumber'])
        results = connection.response
    except LDAPException as e:
        results = e
    maildetailb = ldap_conn.entries
    uid = maildetailb[0]['uid']
    uidNumber = maildetailb[0]['uidNumber']
    userPassword = maildetailb[0]['userPassword']
    mail = maildetailb[0]['mail']
    displayName = maildetailb[0]['displayname']
    vacationActive = maildetailb[0]['vacationActive']
    vacationInfo = maildetailb[0]['vacationInfo']
    telephoneNumber = maildetailb[0]['telephoneNumber']

    #print("BTOTALITE", maildetailb[0])
    #print( "MPKEY", mpkey, "MPK" ,mpk)
    context = {'mpkey': mpkey, 'uid': uid, 'uidNumber':uidNumber, 'mail': mail, 'displayName':displayName, 'vacationActive': vacationActive, 'vacationInfo':vacationInfo, 'telephoneNumber':telephoneNumber}
    return render(request, 'emailusers_detail.html', context)

@login_required(login_url='acceslogin')
def t_email_add(request):
    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            ldap_attr = {}
            #ldap_attr['objectclass'] = ["person", "organizationalPerson", "inetOrgPerson", "posixAccount", "top","shadowAccount"]
            ldap_attr_obj = ["inetOrgPerson", "posixAccount","sambaSamAccount","amavisAccount","shadowAccount","mailAccount", "vacation"]
            ldap_attr['cn'] = form.cleaned_data[ 'cn' ]
            ldap_attr['sn'] = form.cleaned_data[ 'sn' ]
            ldap_attr['mail'] = form.cleaned_data[ 'mail']
            ldap_attr['userPassword'] = form.cleaned_data[ 'userPassword']
            ldap_attr['telephoneNumber'] = form.cleaned_data[ 'telephoneNumber']
            ldap_attr['uid'] = form.cleaned_data[ 'sn' ]+"."+form.cleaned_data['cn']
            useruid = form.cleaned_data[ 'sn' ]+"."+form.cleaned_data['cn']
            ldap_attr['uidNumber'] = uidkey = getuidnumber.getuidnumber()
            ldap_attr['gidNumber'] = 100
            ldap_attr['accountActive'] = 'TRUE'
            ldap_attr['amavisBannedFilesLover'] = 'FALSE'
            ldap_attr['amavisBypassSpamChecks'] = 'FALSE'
            ldap_attr['amavisBypassVirusChecks'] = 'FALSE'
            ldap_attr['amavisSpamKillLevel'] = '2.0'
            ldap_attr['amavisSpamLover'] =  'FALSE'
            ldap_attr['amavisSpamModifiesSubj'] = 'FALSE'
            ldap_attr['amavisSpamTag2Level'] = '2.0'
            ldap_attr['amavisSpamTagLevel'] = '-999'
            ldap_attr['amavisVirusLover'] = 'FALSE'
            ldap_attr['amavisWhiteListSender'] = "contact@adiop.fr"
            ldap_attr['homeDirectory'] = form.cleaned_data['cn']
            ldap_attr['givenName'] = form.cleaned_data['cn']
            ldap_attr['displayName'] = form.cleaned_data['sn']+form.cleaned_data['cn']
            ldap_attr['facsimileTelephoneNumber'] = form.cleaned_data['telephoneNumber']
            ldap_attr['vacationActive'] = str(form.cleaned_data['vacationActive']).upper()
            #ldap_attr['vacationActive'] = True
            ldap_attr['vacationInfo'] = form.cleaned_data['vacationInfo']
            ldap_attr['ou'] = 'Nom Service'
            ldap_attr['postalAddress'] = 'Saisissez adresse'
            ldap_attr['postalCode'] = "11111"
            ldap_attr['postOfficeBox'] = 'Paris'
            ldap_attr['l'] = "Paris"
            ldap_attr['title'] = "usager"
            ldap_attr['mailDrop'] = form.cleaned_data['mail']
            ldap_attr['mailhost'] = 'localhost'# "mailhost" "localhost";
            ldap_attr['loginShell'] = "/bin/false"
            ldap_attr['sambaSID'] = "S-1-5-21-1947415551-996157374-1848903544-2079"
            server = Server('www.adiop.fr')
            conn = Connection(server, user='cn=admin,dc=adiop,dc=net', password='UtBX4PzS')
            #conn.bind()
            # Provide a search base to search for.
            # Bind connection to LDAP server
            ldap_conn = conn
            ldap_conn.bind()
            # this will create testuser inside group1
            #user_dn = "'uid= %s' %(uid), ou=Public,dc=adiop,dc=net"
            user_dn = "uid="+form.cleaned_data[ 'sn' ]+"."+form.cleaned_data['cn']+", ou=Public,dc=adiop,dc=net"
            user_uid = [form.cleaned_data[ 'sn' ]+"."+form.cleaned_data['cn']]
            print(user_dn)
            print(ldap_attr)
            #ldap_conn.search('ou=Public,dc=adiop,dc=net', uid=user_uid,
             #           attributes='uid')

            #ldap_conn.add(dn=user_dn, object_class=ldap_attr_obj, attributes=ldap_attr)
            try:
                ldap_conn.add(dn=user_dn, object_class=ldap_attr_obj, attributes = ldap_attr)
                #response = ldap_conn.add(user_dn, ldap_attr_obj, ldap_attr)
            #except LDAPException as e:
            except:
                response = "Erreur"
                context = {response: response}
                return render(request, 'emailusers_add.html', context)
            return redirect('t_email_detail',uidkey)
            #return render(request, 'emailusers_add.html')
    else:
        form = EmailForm()
    context = {'form': form}
    return render(request, 'emailusers_add.html', context)

@login_required(login_url='acceslogin')

ldap/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
  	<title>CloudSen</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>
      <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'footer/css/ionicons.min.css' %}">

		<link rel="stylesheet" href="{% static 'footer/css/style.css' %}">

      <link rel="stylesheet" href="{% static 'css/style.css' %}">



	</head>
	<body>
 <div class="container">
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
         <a class="navbar-brand" href="#"><h2><font color="#DF6D14">CloudSen</font></h2></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#"><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#"></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <button class="btn btn-warning my-2 my-sm-0" ><a href="{% url 'logout' %}">Se Deconnecter</a></button>
    </form>
  </div>
</nav>
 </div>

    {% block content %}
	  {%endblock%}

	<script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
    <footer class="footer-07">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-md-12 text-center">
                        <h2 class="footer-heading"><a href="#" class="logo"><font color="#DF6D14">CloudSen</font></a></h2>
						<p class="menu">
							<a href="#">Acceuil</a>
							<a href="#">Ftp</a>
							<a href="#">Email</a>
						</p>
						<ul class="ftco-footer-social p-0">
              <li class="ftco-animate"><a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><span class="ion-logo-twitter"></span></a></li>
              <li class="ftco-animate"><a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><span class="ion-logo-facebook"></span></a></li>
              <li class="ftco-animate"><a href="#" data-toggle="tooltip" data-placement="top" title="Instagram"><span class="ion-logo-instagram"></span></a></li>
            </ul>
					</div>
				</div>
				<div class="row mt-5">
					<div class="col-md-12 text-center">
						<p class="copyright"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved |unsrve <a href="https://www.cloudsen.net" target="_blank">CloudSen</a>
					  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
					</div>
				</div>
			</div>
		</footer>




    {% block foot-javascript %}{% endblock %}
	</body>
</html>

ldap/templates/emailusers.html
{% extends 'base.html' %}
{% block content %}
	<body>
	<div class="container">
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Acceuil</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">Ftp<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">Email</a>
      </li>

    </ul>
  </div>
</nav>
		<br>
		<form class="form-inline my-2 my-lg-0">

			<br>
			<div class="container">

		</div>
    </form>
	</div>
	<section class="ftco-section">
		<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Comptes Mail</h2>
				</div>
			    <div>
					<form class="form-inline my-2 my-lg-0">
      <a class="btn btn-secondary my-2 my-sm-0" href="#" type="submit">Ajouter un compte mail</a>
    </form>
				</div>
			</div>


            <div class="container-fluid">
			<div class="row">
				<div class="col-md-12">
					<div class="table-wrap">
						<table class="table table-bordered table-dark table-hover">
						  <thead>
						    <tr>
								<th><h5><font color="#BABABA">uidNumber</font></h5></th>
								<th><h5><font color="#BABABA">Compte</font></h5></th>
								<th><h5><font color="#BABABA">Nom</font></h5></th>
								<th><h5><font color="#BABABA">Email</font></h5></th>

						    </tr>
						  </thead>
			                {% for entry in emailist %}

						  <tbody>
						    <tr>
								<td><a href="/emailusers/{{ entry.uidNumber.value }}">{{ entry.uidNumber.value }}</a></td>
								<td>{{ entry.uid.value }}</td>
						      <td>{{ entry.displayName.value }}</td>
						      <td>{{ entry.mail.value }}</td>
						    </tr>

						  </tbody>
							  {% endfor %}
						</table>

						<center>
						<div class="container p-4">
						<!div class="pagination">
    <span class="step-links">
        {% if emailist.has_previous %}
            <a href="?page=1">&laquo; première</a>
            <a href="?page={{ comptes.previous_page_number }}">précédente</a>
        {% endif %}

        <span class="current">
            Page {{ emailist.number }} of {{ emailist.paginator.num_pages }}.
        </span>

        {% if emailist.has_next %}
            <a href="?page={{ emailist.next_page_number }}">suivante(s)</a>
            <a href="?page={{ emailist.paginator.num_pages }}">dernière &raquo;</a>
        {% endif %}
    </span>
</div>
						</center>


					</div>
				</div>
			</div>
			</div>
	</section>

	<script src="static/js/jquery.min.js"></script>
  <script src="static/js/popper.js"></script>
  <script src="static/js/bootstrap.min.js"></script>
  <script src="static/js/main.js"></script>

	</body>
</html>
{% endblock %}

ldap/templates/emailusers_add.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
 {% load crispy_forms_tags %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}
{{ form.media }}


 <div class="container">

  {% crispy form %}

    {% if form.errors %}
    <div class="alert alert-danger alert-dismissible col-12 mx-1" role="alert">
        <div id="form_errors">
            {% for key, value in form.errors.items %}
                <span class="fieldWrapper">
                    {{ key }}:{{ value }}
                </span>
            {% endfor %}
        </div>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}

 </div>

{% endblock %}
{% block foot-javascript %}
<script>

    // On affiche le calendrier lorsqu'on clique sur le champ date de naissance
    $('#id_dateExpiration').click(function(){
        $(this).parent().data("DatePickerInput").show();
    });
    // On teste la valeur de la date et on la force à vide si elle est mauvaise
    $('#id_dateExpiration').change(function(e){
        e.preventDefault();
        e.stopPropagation();
        var val = $(this).val();
        var format = new RegExp("^\\d{2}\/\\d{2}\/\\d{4}$");
        if(!format.test(val)) {
            $(this).val("");
        }
    });
    // Afficher l'onglet suivant en cliquant sur le bouton suivant
    $('.btnNext').click(function(){
        $('.nav-tabs > .active + li a').trigger('click');
        $(".nav-tabs + .tab-content").find(":input:visible:first").focus();
    });
    // Afficher l'onglet précédent en cliquant sur le bouton précédent
    $('.btnPrevious').click(function(){
        $('.nav-tabs > .active').prev('li').find('a').trigger('click');
        $(".nav-tabs + .tab-content").find(":input:visible:first").focus();
    });
});
</script>

{% endblock %}

ldap/templates/emailusers_delete.html
{% extends 'base.html' %}

{% block content %}
    <p>Etes-vous sûr de vouloir supprimer le compte</p>
     <p>EMAIL {{mail}}</p>
     <h1>Suppression Compte {{uid}}</h1>

     <p>Merci de confirmer la suppression de : {{ displayname }}</p>

     <form action="" method="POST">
     {% csrf_token %}
     <input type="submit" value="Confirmer">
</form>
{% endblock%}

ldap/templates/emailusers_error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Erreur lors de la creation du compte
{{ response }}
</body>
</html>

ldap/templates/indexb.html
{% extends 'base.html' %}
{% block content %}
	<body>
	<div class="container">
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Acceuil</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">Ftp<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">Email</a>
      </li>

    </ul>
  </div>
</nav>
		<br>
		<form class="form-inline my-2 my-lg-0">

			<br>
			<div class="container">

		</div>
    </form>
	</div>
	<section class="ftco-section">
		<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Comptes Mail</h2>
				</div>
			    <div>
					<form class="form-inline my-2 my-lg-0">
      <a class="btn btn-secondary my-2 my-sm-0" href="#" type="submit">Ajouter un compte mail</a>
    </form>
				</div>
			</div>


            <div class="container-fluid">
			<div class="row">
				<div class="col-md-12">
					<div class="table-wrap">
						<table class="table table-bordered table-dark table-hover">
						  <thead>
						    <tr>
								<th><h5><font color="#BABABA">uidNumber</font></h5></th>
								<th><h5><font color="#BABABA">Compte</font></h5></th>
								<th><h5><font color="#BABABA">Nom</font></h5></th>
								<th><h5><font color="#BABABA">Email</font></h5></th>

						    </tr>
						  </thead>
			                {% for entry in emailist %}

						  <tbody>
						    <tr>
								<td><a href="/emailusers/{{ entry.uidNumber.value }}">{{ entry.uidNumber.value }}</a></td>
								<td>{{ entry.uid.value }}</td>
						      <td>{{ entry.displayName.value }}</td>
						      <td>{{ entry.mail.value }}</td>
						    </tr>

						  </tbody>
							  {% endfor %}
						</table>

						<center>
						<div class="container p-4">
						<!div class="pagination">
    <span class="step-links">
        {% if emailist.has_previous %}
            <a href="?page=1">&laquo; première</a>
            <a href="?page={{ comptes.previous_page_number }}">précédente</a>
        {% endif %}

        <span class="current">
            Page {{ emailist.number }} of {{ emailist.paginator.num_pages }}.
        </span>

        {% if emailist.has_next %}
            <a href="?page={{ emailist.next_page_number }}">suivante(s)</a>
            <a href="?page={{ emailist.paginator.num_pages }}">dernière &raquo;</a>
        {% endif %}
    </span>
</div>
						</center>


					</div>
				</div>
			</div>
			</div>
	</section>

	<script src="static/js/jquery.min.js"></script>
  <script src="static/js/popper.js"></script>
  <script src="static/js/bootstrap.min.js"></script>
  <script src="static/js/main.js"></script>

	</body>
</html>
{% endblock %}